### ISSUE TITLE
bug in sample.cpp

### ISSUE THREAD

**Issue by viccto** [handspeaker/RandomForests#2]
void Sample::randomSelectFeature(int*featureIndex,int featureNum,int selectedFeatureNum)
{
	// ......
	for(i=0,j=featureNum-selectedFeatureNum;j<featureNum;++j,++i)
	{
                // if featureNum == selectedFeatureNum, then wrong
		index = rand()%j; 
		// ......
}
so, may be like this:
if(j == 0)
        index = 0;
else
	index = rand()%j;

**Comment by handspeaker** [comment]
thank you for pointing out this bug, it has been fixed

**Comment by handspeaker** [comment]
@csfisher 
thank you for pointing out this bug, it has been fixed
